name: Next.js Deployment to Staging


on:
  push:
    branches:
      - main # change to main
    paths-ignore:
      - 'README.md'
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('./package-lock.json')}}
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          ls
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: dist-files
            path:
                ./out

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist-files-s3
      - name: output contents
        run: ls
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_SECRET_REGION_KEY }}

      - name: Sync build output to S3 bucket
        run: |
          aws s3 sync ./dist-files-s3 s3://fluenty-website