name: Next.js Deployment to Staging


on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('./package-lock.json')}}
      - name: Install dependencies and build
        run: |
          npm install
          npm run export
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
            name: dist-files
            path:
                out

#  deploy:
#    runs-on: ubuntu-latest
#
#    needs: build
#
#    steps:
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: <your-region>  # Specify your AWS region
#
#      - name: Sync build output to S3 bucket
#        run: |
#          aws s3 sync ./out s3://<your-bucket-name>